version: 0.0.{build}
install:
- cmd: pip install cpp-coveralls PyYAML
build:
  verbosity: detailed
before_test:
- cmd: '"%PROGRAMFILES(x86)%\Windows Kits\10\Tools\x64\Devcon.exe" install "%WINDIR%\Inf\Netloop.inf" *MSLOOP'
after_test:
- cmd: >-
    "%PROGRAMFILES(x86)%\Windows Kits\10\Tools\x64\Devcon.exe" remove *MSLOOP
    cpp-coveralls -n --include src\WakeByName.cpp